# Basic build parameters
p="windows"
target="template_release"
tools="no"
debug_symbols="no"

# Generated using https://godot-build-options-generator.github.io
production = "yes"
disable_3d = "yes"
deprecated = "no"
minizip = "no"
module_basis_universal_enabled = "no"
module_bmp_enabled = "no"
module_bullet_enabled = "no"
module_camera_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_jpg_enabled = "no"
module_jsonrpc_enabled = "no"
module_mbedtls_enabled = "no"
module_meshoptimizer_enabled = "no"
module_minimp3_enabled = "no"
module_mobile_vr_enabled = "no"
module_msdfgen_enabled = "no"
module_navigation_enabled = "no"
module_multiplayer_enabled = "no"
module_noise_enabled = "no"
module_ogg_enabled = "no"
module_opensimplex_enabled = "no"
module_openxr_enabled = "no"
module_opus_enabled = "no"
module_pvr_enabled = "no"
module_squish_enabled = "no"
module_stb_vorbis_enabled = "no"
module_tga_enabled = "no"
module_theora_enabled = "no"
module_upnp_enabled = "no"
module_vhacd_enabled = "no"
module_vorbis_enabled = "no"
module_webm_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
module_gdnative_enabled = "no"
module_visual_script_enabled = "no"

# https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html
module_arkit_enabled = "no"
module_assimp_enabled = "no"
module_etc_enabled = "no"
module_recast_enabled = "no"
module_regex_enabled = "no"
module_tinyexr_enabled = "no"
module_xatlas_unwrap_enabled = "no"

